package iq.fib.eamic.license

/**
 * 6-digit activation key check — a direct port of the desktop app's
 * src/main/license.js so codes generated by tools/generate-keys.js (and sent
 * back through FIB) validate identically on Android.
 *
 *   A key is six digits d1 d2 d3 d4 d5 d6.
 *   Valid when: d6 == (d1*2 + d2*3 + d3*4 + d4*5 + d5*6 + SECRET) mod 10
 *
 * SECRET must match the value in the desktop app's secret.js. It is kept out of
 * source control there; mirror the same digit here at build time (e.g. inject
 * via BuildConfig) rather than committing it.
 */
object License {
    // TODO: set to the same digit as the desktop secret.js (0–9), ideally via
    // a BuildConfig field injected from a gitignored gradle property.
    private const val SECRET = 0

    private val WEIGHTS = intArrayOf(2, 3, 4, 5, 6)

    fun checkDigit(firstFive: String): Int {
        var sum = SECRET
        for (i in 0 until 5) sum += (firstFive[i] - '0') * WEIGHTS[i]
        return sum % 10
    }

    /** Keep digits only, so "12 34 56", "123-456" and "EA-..." all normalise. */
    fun normalize(raw: String?): String = (raw ?: "").filter { it.isDigit() }

    fun isValidKey(raw: String?): Boolean {
        val k = normalize(raw)
        if (!Regex("^\\d{6}$").matches(k)) return false
        return (k[5] - '0') == checkDigit(k)
    }
}

enum class LicenseState { TRIAL, EXPIRED, PRO }
